# Generated by Django 4.0.2 on 2022-04-15 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Domlaning ismi')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Qori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Qorining ismi')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_arabic', models.CharField(max_length=30, verbose_name='Arabcha matni')),
                ('title_eng', models.CharField(max_length=30, verbose_name='Inglizcha matni')),
                ('title_uz', models.CharField(max_length=30, verbose_name="O'zbekcha matni")),
                ('slug', models.SlugField(max_length=30, verbose_name='Slug')),
                ('qori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quronuz.qori')),
            ],
        ),
        migrations.CreateModel(
            name='Oyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audios/', verbose_name='Audio')),
                ('text_arabic', models.TextField(max_length=255, verbose_name='Arabcha matni')),
                ('text_uz', models.TextField(max_length=255, verbose_name='Inglizcha matni')),
                ('text_uzb', models.TextField(max_length=255, verbose_name="O'qilishi")),
                ('text_tafsir', models.TextField(max_length=1000, verbose_name="O'zbekchadagi ma'nosi")),
                ('tr_sura', models.IntegerField(default=0, verbose_name='Suradagi t/r')),
                ('tr_umumiy', models.IntegerField(default=0, verbose_name="Qur'ondagi t/r")),
                ('sajda_tafsiya', models.CharField(default="Yo'q", max_length=4, verbose_name='Sajda tafsiya')),
                ('sajda_majburiy', models.CharField(default="Yo'q", max_length=4, verbose_name='Sajda majburiy')),
                ('sura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quronuz.sura')),
            ],
        ),
        migrations.CreateModel(
            name='Maruza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(max_length=100, verbose_name='Video URL')),
                ('popular', models.IntegerField(default=0, verbose_name="Ko'rilganlar soni")),
                ('image', models.ImageField(upload_to='maruzaimg/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('domla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quronuz.domla')),
            ],
        ),
    ]
