# Generated by Django 4.0.4 on 2022-04-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quronuz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AlterModelOptions(
            name='domla',
            options={'verbose_name': 'Domla', 'verbose_name_plural': 'Domlalar'},
        ),
        migrations.AlterModelOptions(
            name='maruza',
            options={'verbose_name': 'Maruza', 'verbose_name_plural': 'Maruzalar'},
        ),
        migrations.AlterModelOptions(
            name='oyat',
            options={'verbose_name': 'Oyat', 'verbose_name_plural': 'Oyatlar'},
        ),
        migrations.AlterModelOptions(
            name='qori',
            options={'verbose_name': 'Qori', 'verbose_name_plural': 'Qorilar'},
        ),
        migrations.AlterModelOptions(
            name='sura',
            options={'verbose_name': 'Sura', 'verbose_name_plural': 'Suralar'},
        ),
    ]
