# Generated by Django 4.0.4 on 2022-04-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quronuz', '0002_category_alter_domla_options_alter_maruza_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
