# Generated by Django 4.0.4 on 2022-04-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quronuz', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
