# Generated by Django 4.0.4 on 2022-04-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quronuz', '0007_sura_delete_category_oyat_sura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.RemoveField(
            model_name='oyat',
            name='sura',
        ),
        migrations.DeleteModel(
            name='Sura',
        ),
    ]
