# Generated by Django 4.0.4 on 2022-04-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quronuz', '0008_province_remove_oyat_sura_delete_sura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_arabic', models.CharField(max_length=30, verbose_name='Arabcha matni')),
                ('title_eng', models.CharField(max_length=30, verbose_name='Inglizcha matni')),
                ('title_uz', models.CharField(max_length=30, verbose_name="O'zbekcha matni")),
                ('slug', models.SlugField(max_length=30, verbose_name='Slug')),
                ('qori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quronuz.qori')),
            ],
            options={
                'verbose_name': 'Sura',
                'verbose_name_plural': 'Suralar',
            },
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
