# Generated by Django 4.0.4 on 2022-05-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quronuz', '0010_oyat_sura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oyat',
            name='text_uz',
        ),
    ]
