# Generated by Django 4.0.4 on 2022-05-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quronuz', '0011_remove_oyat_text_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oyat',
            name='text_arabic',
            field=models.CharField(max_length=255, verbose_name='Arabcha matni'),
        ),
        migrations.AlterField(
            model_name='oyat',
            name='text_tafsir',
            field=models.CharField(max_length=1000, verbose_name="O'zbekchadagi ma'nosi"),
        ),
        migrations.AlterField(
            model_name='oyat',
            name='text_uzb',
            field=models.CharField(max_length=255, verbose_name="O'qilishi"),
        ),
    ]
